"""
Defines abstract syntax tree (AST) classes for Lox expressions.
Generated by GenerateAst.py.
"""

from abc import ABC, abstractmethod
from Token import Token


class Expr(ABC):
    """Base class for all expression AST nodes."""
    @abstractmethod
    def accept(self, visitor):
        pass


class Assign(Expr):
    """Represents an assignment expression (e.g., x = 5)."""
    def __init__(self, name: Token, value: Expr):
        self.name = name
        self.value = value

    def accept(self, visitor):
        return visitor.visit_assign_expr(self)


class Binary(Expr):
    """Represents a binary expression (e.g., 1 + 2)."""
    def __init__(self, left: Expr, operator: Token, right: Expr):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor):
        return visitor.visit_binary_expr(self)


class Call(Expr):
    """Represents a function call expression (e.g., foo(1, 2))."""
    def __init__(self, callee: Expr, paren: Token, arguments: list[Expr]):
        self.callee = callee
        self.paren = paren
        self.arguments = arguments

    def accept(self, visitor):
        return visitor.visit_call_expr(self)


class Get(Expr):
    """Represents a property access expression (e.g., obj.field)."""
    def __init__(self, object: Expr, name: Token):
        self.object = object
        self.name = name

    def accept(self, visitor):
        return visitor.visit_get_expr(self)


class Grouping(Expr):
    """Represents a grouped expression (e.g., (1 + 2))."""
    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor):
        return visitor.visit_grouping_expr(self)


class Literal(Expr):
    """Represents a literal expression (e.g., 42, "hello", true)."""
    def __init__(self, value: object):
        self.value = value

    def accept(self, visitor):
        return visitor.visit_literal_expr(self)


class Logical(Expr):
    """Represents a logical expression (e.g., true and false)."""
    def __init__(self, left: Expr, operator: Token, right: Expr):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor):
        return visitor.visit_logical_expr(self)


class Set(Expr):
    """Represents a property assignment expression (e.g., obj.field = 5)."""
    def __init__(self, object: Expr, name: Token, value: Expr):
        self.object = object
        self.name = name
        self.value = value

    def accept(self, visitor):
        return visitor.visit_set_expr(self)


class Super(Expr):
    """Represents a super expression (e.g., super.method)."""
    def __init__(self, keyword: Token, method: Token):
        self.keyword = keyword
        self.method = method

    def accept(self, visitor):
        return visitor.visit_super_expr(self)


class This(Expr):
    """Represents a this expression (e.g., this)."""
    def __init__(self, keyword: Token):
        self.keyword = keyword

    def accept(self, visitor):
        return visitor.visit_this_expr(self)


class Unary(Expr):
    """Represents a unary expression (e.g., -x, !true)."""
    def __init__(self, operator: Token, right: Expr):
        self.operator = operator
        self.right = right

    def accept(self, visitor):
        return visitor.visit_unary_expr(self)


class Variable(Expr):
    """Represents a variable expression (e.g., x)."""
    def __init__(self, name: Token):
        self.name = name

    def accept(self, visitor):
        return visitor.visit_variable_expr(self)