"""
Defines abstract syntax tree (AST) classes for Lox statements.
Generated by GenerateAst.py.
"""

from abc import ABC, abstractmethod
from Token import Token
from expressions import Expr, Variable


class Stmt(ABC):
    """Base class for all statement AST nodes."""

    @abstractmethod
    def accept(self, visitor):
        pass


class Block(Stmt):
    """Represents a block statement (e.g., { ... })."""

    def __init__(self, statements: list[Stmt]):
        self.statements = statements

    def accept(self, visitor):
        return visitor.visit_block_stmt(self)


class Class(Stmt):
    """Represents a class declaration (e.g., class Foo { ... })."""

    def __init__(
        self, name: Token, superclass: "Variable|None", methods: list["Function"]
    ):
        self.name = name
        self.superclass = superclass
        self.methods = methods

    def accept(self, visitor):
        return visitor.visit_class_stmt(self)


class Expression(Stmt):
    """Represents an expression statement (e.g., 1 + 2;)."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor):
        return visitor.visit_expression_stmt(self)


class Function(Stmt):
    """Represents a function declaration (e.g., fun foo() { ... })."""

    def __init__(self, name: Token, params: list[Token], body: list[Stmt]):
        self.name = name
        self.params = params
        self.body = body

    def accept(self, visitor):
        return visitor.visit_function_stmt(self)


class If(Stmt):
    """Represents an if statement (e.g., if (condition) { ... })."""

    def __init__(self, condition: Expr, then_branch: Stmt, else_branch: Stmt | None):
        self.condition = condition
        self.then_branch = then_branch
        self.else_branch = else_branch

    def accept(self, visitor):
        return visitor.visit_if_stmt(self)


class Print(Stmt):
    """Represents a print statement (e.g., print 42;)."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor):
        return visitor.visit_print_stmt(self)


class Return(Stmt):
    """Represents a return statement (e.g., return 42;)."""

    def __init__(self, keyword: Token, value: Expr | None):
        self.keyword = keyword
        self.value = value

    def accept(self, visitor):
        return visitor.visit_return_stmt(self)


class Var(Stmt):
    """Represents a variable declaration (e.g., var x = 5;)."""

    def __init__(self, name: Token, initializer: Expr | None):
        self.name = name
        self.initializer = initializer

    def accept(self, visitor):
        return visitor.visit_var_stmt(self)


class While(Stmt):
    """Represents a while statement (e.g., while (condition) { ... })."""

    def __init__(self, condition: Expr, body: Stmt):
        self.condition = condition
        self.body = body

    def accept(self, visitor):
        return visitor.visit_while_stmt(self)
